adding failed test cases to ProductInOrganizationServiceTest
JewelleryManagement/jewellery-management-service pull request #105
Opened 2024-04-07 11:33 UTC by berki0

2024-04-08 13:24 UTC, LuboKar reviewed
I'm not sure if the assertions in "successful" tests are necessary because you are stubbing the mapper , which means all the responses will be the same every time, so the assertions will always be true.

2024-04-09 09:09 UTC, VladoKat requested changes

2024-04-09 09:09 UTC, VladoKat commented on src/test/java/jewellery/inventory/unit/service/ProductInOrganizationServiceTest.java
There are some unused mocked fields (productRepository, resourceInProductRepository)

2024-04-09 09:09 UTC, VladoKat commented on src/test/java/jewellery/inventory/unit/service/ProductInOrganizationServiceTest.java
Also, there seems to be no empty lines between the tests on the bottom. Please, format the file

2024-04-15 16:34 UTC, VladoKat approved these changes

2024-04-17 22:47 UTC, merged