[Feature-27-api-documentation] Implemented openapi
JewelleryManagement/jewellery-management-service pull request #35
Opened 2023-10-13 09:54 UTC by Alekseeybg

Implemented openapi for api generation

2023-10-17 06:25 UTC, VladoKat requested changes

2023-10-17 06:25 UTC, VladoKat commented on pom.xml
> +        <!-- https://mvnrepository.com/artifact/org.springdoc/springdoc-openapi-starter-webmvc-ui -->
Remove this comment?

2023-10-18 07:13 UTC, Alekseeybg commented on pom.xml
> +        <!-- https://mvnrepository.com/artifact/org.springdoc/springdoc-openapi-starter-webmvc-ui -->
Fixed

2023-10-18 13:59 UTC, VladoKat approved these changes
ЛГТМ

2023-10-18 14:11 UTC, merged