Feature 37 attach pictures to products
JewelleryManagement/jewellery-management-service pull request #50
Opened 2023-11-15 12:18 UTC by ignatIgnatov

2023-11-16 19:30 UTC, berki0 commented on src/main/java/jewellery/inventory/mapper/ImageDataMapper.java
> +    return product.getId();
this method is not used

2023-11-16 20:03 UTC, berki0 commented on src/main/resources/db/migration/V1_0__insert_user_admin.sql
change the migration name to V1.1

2023-11-16 20:03 UTC, berki0 commented on src/main/resources/db/migration/V2_0__update_resources.sql
change the migration name to V1.2

2023-11-16 20:04 UTC, berki0 commented on src/main/resources/db/migration/V3_0__change_fields_in_product.sql
change the migration name to V1.3

2023-11-16 20:13 UTC, berki0 commented on src/test/resources/static/img/Sample-jpg-image-10mb.jpg
delete image

2023-11-16 20:14 UTC, berki0 commented on src/test/resources/static/img/pearl.jpg
delete image

2023-11-16 20:14 UTC, berki0 commented on src/test/resources/static/img/test.txt
delete test.txt file

2023-11-16 20:43 UTC, berki0 commented on src/main/java/jewellery/inventory/service/ImageService.java
> +import java.nio.file.StandardCopyOption;
Optimize imports

2023-11-16 20:43 UTC, berki0 commented on src/main/java/jewellery/inventory/service/ImageService.java
> +import java.nio.file.StandardCopyOption;
Optimize imports

2023-11-17 06:14 UTC, ignatIgnatov commented on src/main/resources/db/migration/V1_0__insert_user_admin.sql
Done!

2023-11-17 06:14 UTC, ignatIgnatov commented on src/main/resources/db/migration/V2_0__update_resources.sql
Done!

2023-11-17 06:15 UTC, ignatIgnatov commented on src/main/resources/db/migration/V3_0__change_fields_in_product.sql
Done!

2023-11-17 06:16 UTC, ignatIgnatov commented on src/main/java/jewellery/inventory/service/ImageService.java
> +import java.nio.file.StandardCopyOption;
Done!

2023-11-17 06:36 UTC, ignatIgnatov commented on src/test/resources/static/img/Sample-jpg-image-10mb.jpg
I use this file in the integration tests. If I delete them they won't work...

2023-11-17 06:36 UTC, ignatIgnatov commented on src/test/resources/static/img/pearl.jpg
Same thing

2023-11-21 10:24 UTC, VladoKat requested changes
Very minor changes requested. It looks good overall! 
I do have some consideration we should discuss maybe. They are around the filepath and name of the image:
1. Should we include the filePath of the image in the response to the user? Is it useful for them to know this?
2. Should we take the original name of the file and save it in our system or is it better to name the files ourselves. The reason behind this would be if someone uploaded a file with a name with some weird and/or malicious characters. Do we know if this can somehow break our system or mess up the folder where we save the files?

2023-11-21 10:24 UTC, VladoKat commented on src/main/java/jewellery/inventory/service/ProductService.java
> +    return productMapper.mapToProductResponseDto(productRepository.findById(id).orElseThrow(() -> new ProductNotFoundException(id)));
```suggestion
    return productMapper.mapToProductResponseDto(getProduct(id));
```

2023-11-21 10:24 UTC, VladoKat commented on src/test/resources/application.properties
> +multipart.file.max.size=8
If these are the same as the ones in the src/main/resources/application.properties file, then we shouldn't need to specify them here as well

2023-11-22 08:46 UTC, VladoKat approved these changes
Looks good!

2023-11-22 10:12 UTC, merged