Feature 38 sale product return fix
JewelleryManagement/jewellery-management-service pull request #63
Opened 2023-11-27 16:03 UTC by berki0

2023-11-27 20:10 UTC, VladoKat requested changes
The imports seem wrong to me. Let's discuss if you want

2023-11-27 20:10 UTC, VladoKat commented on src/test/java/jewellery/inventory/integration/SaleCrudIntegrationTest.java
> +import static org.junit.Assert.assertNotNull;
Is this right? I see we are using `org.junit.jupiter.api.Assertions.*` everywhere else. Why are we replacing it with `org.junit.Assert.` here?

2023-11-28 16:05 UTC, VladoKat approved these changes
Looks good to me. @Alekseeybg do you want to also take a look before merging?

2023-11-29 17:42 UTC, Alekseeybg approved these changes

2023-11-30 11:29 UTC, merged