Feature 48 add top up cost
JewelleryManagement/jewellery-management-service pull request #66
Opened 2023-12-06 12:42 UTC by ignatIgnatov

2023-12-06 12:50 UTC, ignatIgnatov reviewed
Well done!

2023-12-08 16:06 UTC, CodeLikeAlexito commented on src/main/java/jewellery/inventory/dto/response/ResourcesInUserResponseDto.java
> +  private double dealPrice;
I've noticed that in a lot of places in the project we use double and not BigDecimal datatype. In my opinion BigDecimal is better to be used:

https://www.linkedin.com/pulse/why-we-should-use-bigdecimal-instead-double-java-financial-ismail/
https://www.baeldung.com/java-double-vs-bigdecimal#:~:text=The%20BigDecimal%20class%20offers%20better,accurate%20than%20floating%2Dpoint%20arithmetic.

2023-12-08 16:06 UTC, CodeLikeAlexito commented on src/main/java/jewellery/inventory/service/ResourceInUserService.java
> +  private void addResourceToUserToTransfer(User user, Resource resource, Double quantity) {
Another place where BigDecimal would be good to be used. And plus, above we are using primitive double datatype and here the Double class. This is not very good approach.

2023-12-09 18:17 UTC, VladoKat requested changes
I left comments for a few small changes to the existing implementation. There is something more major I'd like to change though. With the current implementation we'd save the dealPrice in every ResourcesInUserResponse. This means it'd show in the removeQuantity and transferQuantity system events as well. We should make it so that it doesn't show dealPrice in these scenarios. Let's discuss about an approach if you want to.

2023-12-09 18:17 UTC, VladoKat commented on src/main/java/jewellery/inventory/service/ResourceInUserService.java
> +    resourceInUserRepository.save(resourceInUser);
This method isn't very different than the one that just adds resource to user when doing top-up (a.k.a. delivery). We should consider reusing the existing logic and just extend it for the top-up logic.

2023-12-09 18:17 UTC, VladoKat commented on src/test/java/jewellery/inventory/helper/UserTestHelper.java
> +    return requestDto;
```suggestion
    ResourceInUserRequestDto requestDto = createResourceInUserRequestDtoWithoutPrice(userId, resourceId, quantity);
    requestDto.setDealPrice(price);
    return requestDto;
```

2023-12-10 17:53 UTC, VladoKat requested changes
I think if we make the new classes for purchase to extend the existing ResourceInUser model/dto, we'd not need to make some of the additional methods we've made in the ResourceInUser service.

2023-12-10 17:53 UTC, VladoKat commented on src/main/java/jewellery/inventory/dto/request/ResourceInUserRequestDto.java
This seems like an obsolete change?

2023-12-10 17:53 UTC, VladoKat commented on src/main/java/jewellery/inventory/dto/request/ResourcePurchaseRequestDto.java
How about if we made this to extend the ResourceInUserRequestDto? Then it'd just have the dealPrice as a new field. The rest I see are copied from there anyway

2023-12-10 17:53 UTC, VladoKat commented on src/main/java/jewellery/inventory/dto/response/ResourcePurchaseResponseDto.java
Same with this. Can it extend ResourceInUserResponseDto?

2023-12-11 13:06 UTC, ignatIgnatov commented on src/main/java/jewellery/inventory/dto/request/ResourcePurchaseRequestDto.java
Done!

2023-12-11 13:06 UTC, ignatIgnatov commented on src/main/java/jewellery/inventory/dto/response/ResourcePurchaseResponseDto.java
Done!

2023-12-11 21:39 UTC, VladoKat requested changes
Last minor change/question. It looks great otherwise.

2023-12-11 21:39 UTC, VladoKat commented on src/main/java/jewellery/inventory/service/ResourceInUserService.java
> +    }
Is this null check necessary? From what I see on line 97 (findResourceInUser**OrThrow**) resourceInUser can't be null.

2023-12-12 06:44 UTC, ignatIgnatov commented on src/main/java/jewellery/inventory/service/ResourceInUserService.java
> +    }
I forgot to put the removeQuantityFromResource method before the if-statement. This method can return null value of ResourceInUser. Now I fixed it.

2023-12-12 07:40 UTC, VladoKat approved these changes
LGTM

2023-12-12 08:28 UTC, merged